[build]
  # Build command for Nuxt with Netlify preset
  command = "npm run build"
  # Netlify automatically detects the output directory
  publish = "dist"
  
[functions]
  directory = ".netlify/functions-internal"

[build.environment]
  # Specify Node.js version explicitly
  NODE_VERSION = "20.19.0"

# No custom redirects - let Nuxt/Nitro handle all routing
