[build]
  # Build command for Nuxt with Netlify preset
  command = "npm run build"
  # Netlify automatically detects the output directory
  publish = "dist"

[build.environment]
  # Specify Node.js version explicitly
  NODE_VERSION = "20.19.0"

# No redirects needed - Netlify preset handles routing automatically
# The renderer function will handle all routes
