[build]
  # Build command for Nuxt with Netlify preset (production only)
  command = "npm run build"
  # Netlify automatically detects the output directory
  publish = "dist"

[dev]
  # Development server command
  command = "nuxt dev"
  targetPort = 3000
  framework = "#custom"
  autoLaunch = false
  
[functions]
  directory = ".netlify/functions-internal"

[build.environment]
  # Specify Node.js version explicitly
  NODE_VERSION = "20.19.0"

# Disable AI Gateway if not needed
[ai]
  enabled = false

# No custom redirects - let Nuxt/Nitro handle all routing
